name: pindmd3-firmware

on:
  push:

  pull_request:

jobs:
  pio-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3"

      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Build pindmd3-firmware
        run: |
          pio run -e teensy31

      - uses: actions/upload-artifact@v4
        with:
          name: pindmd3-firmware
          path: .pio/build/teensy31/firmware.hex
